source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'N42WebView_Example' do
  pod "N42WebView", :path => "../"
end

target 'N42WebView_Tests' do
  pod "N42WebView", :path => "../"

  #pod 'Quick', '~> 0.8.0'
  #pod 'Nimble', '3.0.0'
  #pod 'FBSnapshotTestCase'
  #pod 'Nimble-Snapshots'
end
